training:
  # Maximum number of epochs
  epochs: 100
  # Device on which the model will be trained. Set 'cpu' to train/infer on CPU
  device: cpu

  dataloader:
    batch_size: 32
    shuffle: True
    pin_memory: False
  
  optimizer:
    name: AdamW
    args:
      lr: 3e-5
      eps: 1e-08
      betas: [0.9, 0.999]
      weight_decay: 0.01
  
  # Whether to use mixed precision training instead of full precision (FP32)
  amp: true
  # Early stopping configs
  early_stop:
    # Whether to use early stopping, (Default: false)
    enabled: false
    # Patience for early stoppings
    patience: 4000
    # Criteria to be monitored for early stopping
    criteria: loss
    # Whether the monitored criteria should be minimized for early stopping
    minimize: true
    

# Environment configuration
env:
  # Base directory of the repo, populated when config is loaded
  base_dir: '/Users/tmsantos/Documents/TTS_Augmentation/tts_data_augmentation'
  # Directory for storing datasets and models
  data_root: ${env.base_dir}/data
  # Directory for experiments, logs, output samples etc.
  save_dir: ${env.base_dir}/filtering_framework/save
  # Directory for saving models, logs and checkpoints for each experiment
  experiments_dir: ${env.save_dir}/experiments
  # Experiment id
  experiment_id: model1
